#UI Transitions - container/menu transition animations
#Mon Oct 05 23:25:46 CST 2026
allowLookDuringClose=true
animateAllScreens=false
animateDim=false
animatePanel=true
animateSameTypeSwitch=true
animateSubtitles=false
closeToBottom=true
curve=cubic
durationMs=300
enabled=true
excludedScreens=
extraScreens=mezz.jei,dev.emi.emi,me.shedaniel.rei
fade=true
fadeDim=true
fadeItems=true
fadeText=true
jelly=0.0
offset=120.0
openFromBottom=true
overlayModsFadeOnly=true
staggerClose=true
